# Generated by Django 5.0.2 on 2025-03-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0003_delete_alarm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("is_test", models.BooleanField(default=False)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_error", models.TextField(blank=True, null=True)),
                ("notification_attempts", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "whatsapp_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "notification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alarms_new",
                        to="subjects.subjectqr",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alarms_new",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm",
                "verbose_name_plural": "Alarms",
                "ordering": ["-timestamp"],
            },
        ),
    ]
