# Generated by Django 5.0.2 on 2025-03-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="notification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("SENT", "Sent"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
