# Generated by Django 5.0.2 on 2025-04-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0002_alter_alarm_notification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="issue_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
