# Generated by Django 5.0.2 on 2025-04-08 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0004_standardize_related_names_and_add_indexes"),
    ]

    operations = [
        # Add resolution fields to Alarm model
        migrations.AddField(
            model_name="alarm",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="scanned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.user",
            ),
        ),
        
        # Create NotificationAttempt model
        migrations.CreateModel(
            name="NotificationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "alarm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_attempts",
                        to="alarms.alarm",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custodians.custodian",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Attempt",
                "verbose_name_plural": "Notification Attempts",
                "ordering": ["-sent_at"],
            },
        ),
    ] 