# Generated by Django 5.0.2 on 2025-04-08 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "alarms",
            "0006_rename_notification_attempts_alarm_notification_attempt_count_and_more",
        ),
        ("custodians", "0006_alter_custodian_verification_code_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationattempt",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AddField(
            model_name="notificationattempt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notificationattempt",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="notificationattempt",
            index=models.Index(fields=["created_at"], name="notif_created_at_idx"),
        ),
    ]
