# Generated by Django 5.0.2 on 2025-04-08 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0007_alter_notificationattempt_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
