# Generated by Django 5.0.2 on 2025-04-10 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alarms", "0009_alarm_message_sid_alter_alarm_location_and_more"),
        ("subjects", "0007_delete_alarm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alarm",
            name="issue_type",
        ),
        migrations.AddField(
            model_name="alarm",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="is_anonymous",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="situation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INJURED", "Subject Injured"),
                    ("LOST", "Subject Lost"),
                    ("CONTACT", "Subject Requesting Contact"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="alarm",
            index=models.Index(
                fields=["situation_type"], name="alarms_situation_type_idx"
            ),
        ),
    ]
