name: keryu3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - django=5.0
  - python-dotenv=1.0
  - gunicorn=21.2
  - whitenoise=6.6
  - pip
  - pip:
    - django-cors-headers==4.3.1
    - djangorestframework==3.14.0
    - qrcode==7.4.2
    - Pillow==10.2.0
    - python-whatsapp-api==1.0.4
    - django-phonenumber-field[phonenumbers]==7.3.0
    - drf-yasg==1.21.7  # For API documentation 