# Generated by Django 5.0.8 on 2025-03-12 22:37

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custodians', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='emergency_phone',
        ),
        migrations.AddField(
            model_name='subject',
            name='doctor_address',
            field=models.TextField(blank=True, help_text="Doctor's office address"),
        ),
        migrations.AddField(
            model_name='subject',
            name='doctor_name',
            field=models.CharField(blank=True, help_text='Primary care physician', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='doctor_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Doctor's contact number", max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='subject',
            name='doctor_speciality',
            field=models.CharField(blank=True, help_text="Doctor's speciality", max_length=100),
        ),
    ]
