# Generated by Django 5.0.8 on 2025-03-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custodians', '0003_remove_subject_emergency_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
