# Generated by Django 5.0.2 on 2025-04-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custodians", "0004_delete_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="custodian",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="custodian",
            name="verification_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="custodian",
            name="verification_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="custodian",
            name="verification_code_timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
