# Generated by Django 5.0.2 on 2025-04-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custodians", "0005_custodian_phone_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custodian",
            name="verification_code_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
