# Generated by Django 5.0.2 on 2025-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="last_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alarm",
            name="notification_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="alarm",
            name="notification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("ERROR", "Error"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="alarm",
            name="whatsapp_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
