# Generated by Django 5.0.2 on 2025-03-20 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_alarm_last_attempt_alarm_notification_attempts_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alarm",
        ),
    ]
