# Generated by Django 5.0.2 on 2025-04-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0006_alarm"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alarm",
        ),
    ]
